# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: lychee
on:
  schedule:
    - cron: '0 0 * * *' # do it every day
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lychee-link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
