name: Update version identifiers for quick scan

on:
  schedule:
    - cron: '0 0 * * 0' # do it every week

jobs:
  update_quick_versions:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt-get update -y
        mkdir external
        git clone https://github.com/fkie-cad/nvd-json-data-feeds.git external/nvd-json-data-feeds
    - name: update version identifiers
      run: |
        ./helpers/generate_quick_scan_bin_version_strings.sh
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update version identifiers for quick profile
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: quick_version_update
        delete-branch: true
        title: 'Quick version identifier update'
        body: |
          Update report
          - Updated the version identifiers for the quick scanning profile
        labels: |
          db_update
          automated pr
        milestone: 0
        draft: false
